### ISSUE TITLE
是否可以自定义提供者的ip

### ISSUE THREAD

**Issue by GenjiLemon** [dazejs/dubbo-provider#232]
微服务的情况下，使用不同的云资源，dubbo-provider如何自定义提供者的ip呢？

**Comment by GenjiLemon** [comment]
我翻阅到os.networkInterfaces的源码，没有发现能和配置文件结合的地方，但是实际情况下系统取到的不是我想要的ip地址

**Comment by czewail** [comment]
@GenjiLemon #233

**Comment by GenjiLemon** [comment]
感谢您的更新，dubbo-provider解决了我node.js跨语言微服务的困惑。此次更新后我在本地测试可以正常使用，解决了我的问题。
但是我发现无法通过只修改dubbo.ts中的ip字段完成全局配置，@dubbo.ip的方式是可以正常生效的的。
对我来说有一种可以生效已经够了，全局的方式是我测试出来的可能缺陷。
